# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - unknow-analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: mcr.microsoft.com/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_218CCDBA26584512BA045923AC6E31AA }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_23946FBEA4504D4BBDC3F25076219DA3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mcr.microsoft.com/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_218CCDBA26584512BA045923AC6E31AA }}/appsvc/staticsite:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65EFB51333034B829A1BAD7FC0F67B17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA7A567F8EF447B8B6A5269287A6BAA8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9785301B4824447AAF6FC7EE0FEE0F9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unknow-analysis'
          slot-name: 'Production'
          images: 'mcr.microsoft.com/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_218CCDBA26584512BA045923AC6E31AA }}/appsvc/staticsite:${{ github.sha }}'
          